# Generated by Django 5.0.7 on 2025-06-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtadminprofile',
            name='district_code',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stateadminprofile',
            name='state_code',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
