# Generated by Django 5.0.7 on 2025-07-28 08:56

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_price_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_subscription',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bhooswamiprofile',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bhooswamiprofile',
            name='land_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bhooswamiprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bhooswamiprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.CustomUser.rename_profile_picture),
        ),
        migrations.AlterField(
            model_name='krisshakprofile',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='krisshakprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='krisshakprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
