services:
  - type: web
    name: ekrisshak2
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn ekrisshak2.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
