# Generated by Django 5.0.7 on 2025-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(blank=True, choices=[('krisshak', 'Krisshak'), ('bhooswami', 'Bhooswami'), ('district_admin', 'District Admin'), ('state_admin', 'State Admin')], max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_to', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
