# Generated by Django 5.0.7 on 2025-06-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact Messages'},
        ),
    ]
