# Generated by Django 5.0.7 on 2025-06-12 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bhooswami',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bhooswami_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='krisshak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krisshak_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
