# Generated by Django 5.0.7 on 2025-06-17 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('bhooswami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bhooswami_requests', to=settings.AUTH_USER_MODEL)),
                ('krisshak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krisshak_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
