# Generated by Django 5.0.7 on 2025-06-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_payment_status_appointmentrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentrequest',
            options={'verbose_name': 'Appointment Requests'},
        ),
    ]
