# Generated by Django 5.0.7 on 2025-07-28 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointmentrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentrequest',
            options={'verbose_name': 'Appointment Request'},
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='bhooswami',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='krisshak',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
