# Generated by Django 5.0.7 on 2025-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('contact', 'Contact'), ('calendar', 'Calender'), ('payment', 'Payment'), ('requests', 'Requests'), ('system', 'System')], max_length=20),
        ),
    ]
